<!-- jquery plugins here-->
<script src="{{ asset('assets/js/jquery-1.12.1.min.js') }}"></script>
<!-- popper js -->
<script src="{{ asset('assets/js/popper.min.js') }}"></script>
<!-- bootstrap js -->
<script src="{{ asset('assets/js/bootstrap.min.js') }}"></script>
<!-- magnific js -->
<script src="{{ asset('assets/js/jquery.magnific-popup.js') }}"></script>
<!-- swiper js -->
<script src="{{ asset('assets/js/owl.carousel.min.js') }}"></script>
<!-- masonry js -->
<script src="{{ asset('assets/js/masonry.pkgd.js') }}"></script>
<!-- masonry js -->
<script src="{{ asset('assets/js/jquery.nice-select.min.js') }}"></script>
<script src="{{ asset('assets/js/gijgo.min.js') }}"></script>
<!-- contact js -->
<script src="{{ asset('assets/js/jquery.ajaxchimp.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.form.js') }}"></script>
<script src="{{ asset('assets/js/jquery.validate.min.js') }}"></script>
<script src="{{ asset('assets/js/mail-script.js') }}"></script>
<script src="{{ asset('assets/js/contact.js') }}"></script>
<!-- custom js -->
<script src="{{ asset('assets/js/custom.js') }}"></script>